CONFIG_GPIO=y
CONFIG_PRINTK=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_LOG=n
CONFIG_BOOT_BANNER=n
CONFIG_DAC=y


# ─── SPI master ───────────────────────────────────────────────
CONFIG_SPI=y
# ─── PWM output (LEDC) ────────────────────────────────────────
CONFIG_PWM=y
 
# ─── PWM capture (MCPWM) ──────────────────────────────────────
CONFIG_PWM_CAPTURE=y
 
